sudo: required

services:
  - docker

language: ruby
rvm:
 - "2.0.0"

install:
  - gem install bundler
  - bundle install
  
script:
  - docker info
  - docker build -t pgarbe/tatsu-hubot:v_$CIRCLE_BUILD_NUM .

deploy:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker push pgarbe/tatsu-hubot:v_$CIRCLE_BUILD_NUM
  - bundle exec rake create_or_update
